services:
  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq-messaging
    ports:
      - "5672:5672"   # RabbitMQ standard port
      - "15672:15672" # RabbitMQ management UI
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 2s
      retries: 5
      
  booking-service:
    image: booking-service:latest
    container_name: booking-service
    ports:
      - "8083:8083"
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - .env
    environment:
      # RabbitMQ connection string - note the service name must match
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq-messaging:5672

  email-service:
    image: email-service:latest
    container_name: email-service
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - .env
    environment:
      # RabbitMQ connection string - note the service name must match
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq-messaging:5672 